version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  worker:
    build:
      context: ./worker
    container_name: celery-worker
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - backend
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
